services:
  backend:
    build: ./backend
    container_name: rolemining-backend
    restart: unless-stopped
    environment:
      - MOCK_AD=0
      - JWT_SECRET=change-me-in-prod
      - JWT_EXPIRE_MINUTES=240
      - UVICORN_WORKERS=1
      - LDAP_FETCH_ALL_ATTRIBUTES=0
      - LDAP_PAGE_SIZE=1000
      - LDAP_SEARCH_TIME_LIMIT=60
      - APP_LOGIN_USER=admin #Change here for your preferred username
      - APP_LOGIN_PASS=admin123 #Change here for your preferred password
    ports:
      - "9000:8000"

  frontend:
    build: ./frontend
    container_name: rolemining-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
