services:
  backend:
    build: ./backend
    container_name: rolemining-backend
    environment:
      - MOCK_AD=0
      - JWT_SECRET=change-me-in-prod
      - JWT_EXPIRE_MINUTES=240
      - APP_LOGIN_USER=admin #Change here for your preferred username
      - APP_LOGIN_PASS=admin123 #Change here for your preferred password
    ports:
      - "9000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: rolemining-frontend
    environment:
      - VITE_API_BASE=http:// #Place your ip or dns here:9000  
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
